modLoader = "javafml"
loaderVersion = "[44,)"
license = "MIT"

[[mods]]
modId = "duckies"
version = "${version}"
displayName = "Duckies"
logoFile = "logo.png"
authors = "Jirho"
description = '''
A mod that adds ducks and stuff.
'''

[[dependencies.duckies]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.duckies]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.duckies]]
modId = "architectury"
mandatory = true
versionRange = "[7.1.86,)"
ordering = "AFTER"
side = "BOTH"
