modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "duckies"
version = "${version}"
displayName = "Duckies"
logoFile = "logo.png"
authors = "Jirho"
description = '''
A mod that adds ducks and stuff.
'''

[[dependencies.duckies]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.duckies]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.duckies]]
modId = "architectury"
type = "required"
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"
